cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('cart/add/<int:product_id>', views.add_to_cart, name="cart_add"),
    path('cart/', views.cart_detail, name='cart_detail'),

    path('cart/update/<int:item_id>/', views.update_cart_item, name='cart_update'),

    path('cart/remove/<int:item_id>/', views.remove_from_cart, name='cart_remove'),
]

ecommerce_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),

    path("accounts/", include("users.urls")),
    path("", include("mainapp.urls")),
    path("", include("cart.urls")),
    path("", include("products.urls")),

    path("", include("orders.urls")),

]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views
from .views import CategoryCreateView, CategoryUpdateView, CategoryDeleteView

urlpatterns = [
    path('manage/', views.ManageCatalogView.as_view(), name='manage_catalog'),

    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('<slug:category_slug>/', views.category_view, name='category'),
    path('product/<slug:product_slug>/', views.product_detail, name='product_detail'),


    path('product/reviews/create/', views.create_review, name='create_review'),
    path('product/reviews/delete/<int:review_id>/', views.delete_review, name='delete_review'),

    path('storemanagers/products/add/', views.add_product, name='add_product'),


    # Gestione prodotti
    path('product/<int:product_id>/modify/', views.modify_product, name='modify_product'),
    path('product/<int:product_id>/delete/', views.delete_product, name='delete_product'),

    # Gestione categorie
    path('categories/add/', CategoryCreateView.as_view(), name='category_add'),
    path('categories/<int:pk>/edit/', CategoryUpdateView.as_view(), name='category_edit'),

    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete'),

]

products/models.py
from decimal import Decimal,ROUND_HALF_UP

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Max
from django.utils import timezone
from cloudinary.models import CloudinaryField

from ecommerce_core import settings
from orders.models import OrderItem, Order

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True)

    if settings.USE_CLOUDINARY:
        image = CloudinaryField('category_image', blank=True, null=True, folder='ecommerce/categories_images/')
    else:
        image = models.ImageField(upload_to='categories_images/', blank=True, null=True)

    class Meta:
        verbose_name_plural = "Categories"
        ordering = ["name"]

    def __str__(self):
        return self.name

    @property
    def max_price_product(self):
        max_price = self.products.aggregate(Max('price'))['price__max']
        return self.products.filter(price=max_price).first().price if max_price else Decimal('0.00')


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=150)
    slug = models.SlugField(unique=True)
    short_description = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # discounts
    discount_percentage = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        default=0.00,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text="Percentage of discount applied to the product (0-100%)"
    )
    discount_start_date = models.DateTimeField(
        blank=True,
        null=True,
        help_text="Start date of the current discount"
    )
    discount_end_date = models.DateTimeField(
        blank=True,
        null=True,
        help_text="End date of the current discount "
    )
    is_discount_active = models.BooleanField(
        default=False,
        help_text="Activate/deactivate the current discount"
    )

    class Meta:
        ordering = ["-created_at"]

    @property
    def get_main_image(self):
        main_image = self.images.filter(is_main=True).first()
        return main_image.image.url if main_image else f'https://placehold.co/300x300/eee/333?text={self.name}'

    @property
    def has_active_discount(self):
        if not self.is_discount_active or self.discount_percentage <= 0:
            return False

        now = timezone.now()

        if self.discount_start_date and self.discount_end_date:
            return self.discount_start_date <= now <= self.discount_end_date
        elif self.discount_start_date:
            return now >= self.discount_start_date
        elif self.discount_end_date:
            return now <= self.discount_end_date

        # If no dates are set, assume the discount is always active
        return True

    @property
    def discounted_price(self):
        if self.has_active_discount:
            discount_amount = self.price * (self.discount_percentage / 100)
            discounted = self.price - discount_amount
            return discounted.quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        return self.price.quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)

    @property
    def discount_amount(self):
        if self.has_active_discount:
            return (self.price * (self.discount_percentage / 100)).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        return Decimal('0.00')

    @property
    def price_display(self):
        return {
            'original_price': self.price,
            'discounted_price': self.discounted_price,
            'discount_amount': self.discount_amount,
            'discount_percentage': self.discount_percentage,
            'has_discount': self.has_active_discount
        }

    @property
    def mean_rating(self):
        reviews = self.reviews.all()
        if not reviews:
            return Decimal('0.0')

        total_rating = sum(review.rating for review in reviews)

        average = Decimal(str(total_rating)) / Decimal(str(reviews.count()))
        return average.quantize(Decimal('0.1'), rounding=ROUND_HALF_UP)

    def star_count(self):
        mean_rating = self.mean_rating
        if mean_rating == Decimal('0.0'):
            return 0

        return int(mean_rating.to_integral_value(rounding=ROUND_HALF_UP))

    @property
    def review_count(self):
        return self.reviews.count()




def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(
        'Product',
        on_delete=models.CASCADE,
        related_name='images',
        help_text="product to which this image belongs"
    )
    if settings.USE_CLOUDINARY:
        image = CloudinaryField('product_image', blank=True, null=True, folder='ecommerce/product_images/')
    else:
        image = models.ImageField(upload_to='product_images/', blank=True, null=True)

    is_main = models.BooleanField(
        default=False,
        help_text="indicates if this is the main image for the product"
    )
    alt_text = models.CharField(
        max_length=255,
        blank=True,
        help_text="alternative text for the image (SEO friendly)"
    )
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-is_main', 'uploaded_at']
        verbose_name = "Product Image"
        verbose_name_plural = "Product Images"

    def __str__(self):
        return f"{'main pic' if self.is_main else 'secondary pic'} – {self.product.name}"


class Review(models.Model):
    product = models.ForeignKey(
        'Product',
        on_delete=models.CASCADE,
        related_name='reviews'
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='reviews'
    )
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name='reviews',
        help_text="Order from which this review originates"
    )

    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    review_text = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ['product', 'user']
        indexes = [
            models.Index(fields=['product', '-created_at']),
            models.Index(fields=['user', '-created_at']),
        ]

    def clean(self):
        super().clean()
        if not self.user_has_purchased_product():
            raise ValidationError("You can only review products you have purchased.")

    def user_has_purchased_product(self):
        return OrderItem.objects.filter(
            order__user=self.user,
            product=self.product,
            order__status='delivered'
        ).exists()

    def __str__(self):
        return f"{self.user.username} - {self.product.name} ({self.rating}/5)"

templates/products/product_card.html
<div class="card product-card shadow-sm position-relative h-100">
    <!-- Badge Stock Status -->
    {%if  actual_section == 'manage_catalog' %}
        {% if product.stock <= 5 %}
            <span
                    class="position-absolute top-10 start-100 badge rounded-pill bg-danger"
                    style="transform: translate(-75px, 7px);"
            >
                Low stock
            </span>
        {% elif product.stock <= 10 %}
            <span class="position-absolute top-10 start-100  badge rounded-pill bg-warning"
                  style="transform: translate(-100px, 7px);">
                Medium stock
            </span>
        {% endif %}
    {% endif %}

    {% if actual_section != 'manage_catalog' %}
    <a href="{% url 'product_detail' product.slug %}" class="stretched-link"></a>
    {% endif %}

    {% if product.has_active_discount %}
        <span class="badge bg-danger position-absolute top-0 start-0 m-2">Sale</span>
    {% endif %}

    <img src="{{ product.get_main_image|default:'https://placehold.co/253x235/f8f9fa/333?text=Product+Image' }}"
         class="card-img-top p-3"
         alt="{{ product.name }}"
         style="height: 250px; object-fit: contain;">

    <div class="card-body d-flex flex-column text-center">
        <h5 class="card-title text-dark">{{ product.name }}</h5>
        <p class="card-text text-muted small">{{ product.short_description }}</p>
{#        <p class="card-text text-muted small">{{ product.description }}</p>#}

        <div class="mb-2">
            {% comment %} Prendo rating e review_count, con fallback {% endcomment %}
            {% with r=product.star_count|default_if_none:"3.5"|floatformat:"1"%}
                {% with intpart=r|slice:":1" halfdigit=r|slice:"2:3" revcount=product.review_count|default_if_none:"127"%}

                    {% if product.mean_rating %}
                        {% for _ in "12345" %}
                            {% with idx=forloop.counter|stringformat:"s" %}
                                {% if idx <= intpart %}
                                    <i class="fa-solid fa-star text-warning"></i>
                                {% elif halfdigit == "5" and idx == intpart|add:"1" %}
                                    <i class="fa-solid fa-star-half"></i>
                                {% else %}
                                    <i class="fa-regular fa-star"></i>
                                {% endif %}
                            {% endwith %}
                        {% endfor %}
                    {% endif %}

                    <small class="text-muted">({{ revcount }} reviews)</small>

                {% endwith %}
            {% endwith %}
        </div>

        {% if product.stock == 0 %}
            <p class="text-danger fw-bold mb-2 mt-2">Out of Stock</p>
        {% else %}
            <span class="badge bg-success w-auto mx-auto mb-3 mt-2">In stock: {{ product.stock }}</span>
        {% endif %}

        {% if product.has_active_discount %}
            <div class="text-center mt-auto">
                <div>
                    <span class="text-decoration-line-through text-muted me-1">€{{ product.price }}</span>
                    <span class="badge bg-success">-{{ product.discount_percentage }}%</span>
                </div>
                <div class="fw-bold text-primary fs-5 mt-2">€{{ product.discounted_price }}</div>
            </div>
        {% else %}
            <div class="fw-bold text-primary fs-5 mt-auto">€{{ product.price }}</div>
        {% endif %}

        {% if actual_section == 'manage_catalog' %}
            <div class="mt-3">
                <div class="mt-auto justify-content-center gap-5">
                    <a href="{% url 'product_detail' product.slug %}" class="btn btn-sm btn-primary">
                        <i class="fas fa-eye"></i> View
                    </a>
                    <a href="{% url 'modify_product' product.id %}" class="btn btn-sm btn-warning">
                        <i class="fas fa-edit"></i> Edit
                    </a>
                    <form method="post" action="{% url 'delete_product' product.id %}" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to eliminate the product named: {{ product.name }}?')">
                            <i class="fas fa-trash"></i> Delete
                        </button>
                    </form>
                </div>
        </div>
        {% else %}

        {% endif %}
    </div>
</div>

<style>
    .product-card {
        border-radius: 0.75rem;
        overflow: hidden;
        transition: transform 0.3s ease, box-shadow 0.3s ease;
        cursor: pointer;
    }
    .product-card:hover {
        transform: scale(1.05);
        box-shadow: 0 0.75rem 1.5rem rgba(0,0,0,0.15);
        z-index: 2;
    }
    .product-card .card-body {
        background-color: #f8f9fa;
        padding: 1.25rem;
    }
    .product-card .badge {
        border-radius: 0.5rem;
    }
</style>

templates/products/product_filter_section.html
{% load static %}
<div class="card shadow-sm sticky-top" style="top: 20px;">
    <div class="card-header">
        <h5 class="mb-0">Filter and order products</h5>
    </div>
    <div class="card-body">
        <form method="get" action="">
            <!-- Category Filter -->
            <h6>Category</h6>
            <select class="form-select mb-4" name="category" id="categoryDropdown">
                <option value="">All categories</option>
                {% for category in category_list %}
                    <option value="{{ category.slug }}" {% if selected_category == category.slug %}selected{% endif %}>
                        {{ category.name }}
                    </option>
                {% empty %}
                    <option disabled>No categories found</option>
                {% endfor %}
            </select>

            <!--Discount Filter-->
            <div class="form-check mb-4 mt-4">
                <input
                        class="form-check-input"
                        type="checkbox"
                        id="onsaleCheckbox"
                        name="discount"
                        value="1"
                        {% if request.GET.discount %}checked{% endif %}
                >
                <label class="form-check-label" for="onsaleCheckbox">
                    <strong>On sale </strong>
                </label>
            </div>

            <!-- stars Filter -->
            <div class="mb-3">
                <label class="mt-3"><strong>Minimum Rating:</strong></label>
                <!-- Hidden input to store the selected rating -->
                <input type="hidden" name="min_rating" id="minRatingInput" value="{% if request.GET.min_rating %}{{ request.GET.min_rating }}{% endif %}">
                <div class="review-stars mt-1" id="ratingFilter" data-rating="{% if request.GET.min_rating %}{{ request.GET.min_rating }}{% else %}0{% endif %}">
                    {% for i in "12345" %}
                        <span class="star" data-value="{{ forloop.counter }}" style="cursor: pointer;">
                            <i class="fa-regular fa-star"></i>
                        </span>
                    {% endfor %}
                </div>
                <small class="text-muted">Click to filter by minimum rating</small>
            </div>


            <!-- Price Filter -->
            <h6>Max price</h6>
            <label for="priceRange" class="form-label">
                Max price: <span id="priceValue">{% if selected_max_price %}{{ selected_max_price}}€ {% else %} - {% endif %}</span>
            </label>
            <input
                    type="range"
                    class="form-range"
                    min="0"
                    max="{{max_price}}"
                    id="priceRange"
                    value="{% if selected_max_price %}{{selected_max_price}}{% else %}0{% endif %}"
                    oninput="handlePriceInput(this)"
            />
            <!-- Ordinamento -->
            <h6>Order by</h6>
            <select class="form-select mb-4" name="order">
                <option value="" {% if not selected_order %}selected{% endif %}>Predefined</option>
                <option value="1" {% if selected_order == '1' %}selected{% endif %}>Price: Low to High</option>
                <option value="2" {% if selected_order == '2' %}selected{% endif %}>Price: High to Low </option>
                <option value="3" {% if selected_order == '3' %}selected{% endif %}>recent</option>
            </select>

            <button type="submit" class="btn btn-sm btn-outline-dark mt-2" style="position: relative">Apply filters</button>
        </form>
        <a href="{% if actual_section == 'product_list'%}{% url 'product_list' %}{% else %}{% url 'manage_catalog' %}{% endif %}"
           id="clearFilters"
           class="btn btn-sm btn-outline-secondary mt-2 d-none"
           style="position:absolute; top:480px; left:120px;">
            Clear filters
        </a>
    </div>
</div>

<script

        src="{% static 'js/managerareas/filter_manager.js' %}">
</script>

templates/products/product_listing.html
{% extends "base.html" %}
{% load static %}

{% block title %}Catalog - ShopFrontier{% endblock title %}

{% block content %}
    <div class="container my-5">
        <!-- Intestazione della Pagina -->
        <div class="row text-center mb-5">
            <div class="col-12">
                <h1>Our Catalog</h1>
                <p class="lead">Explore all our product to find all you need.</p>
            </div>
        </div>

        <div class="row">
            <!-- Colonna Sinistra: Filtri e Ordinamento -->
            <div class="col-lg-3">
                {% include "products/product_filter_section.html" with category_list=category_list selected_max_price=selected_max_price select_order=selected_order selected_category=selected_category actual_section='product_list'%}

                {#                <div class="card shadow-sm sticky-top" style="top: 20px;">#}
{#                    <div class="card-header">#}
{#                        <h5 class="mb-0">Filter and order products</h5>#}
{#                    </div>#}
{#                    <div class="card-body">#}
{#                        <form method="get" action="">#}
{#                            <!-- Filtro per Categoria -->#}
{#                            <h6>Category</h6>#}
{#                            <select class="form-select mb-4" name="category" id="categoryDropdown">#}
{#                                <option value="">Tutte le Categorie</option>#}
{#                                {% for category in category_list %}#}
{#                                    <option value="{{ category.slug }}" {% if selected_category == category.slug %}selected{% endif %}>#}
{#                                        {{ category.name }}#}
{#                                    </option>#}
{#                                {% empty %}#}
{#                                    <option disabled>No categories found</option>#}
{#                                {% endfor %}#}
{#                            </select>#}
{##}
{#                            <!-- Filtro per Prezzo -->#}
{#                            <h6>Max price</h6>#}
{##}
{#                            <label for="priceRange" class="form-label">#}
{#                                Max price: €<span id="priceValue">{{ selected_max_price|default:1000 }}</span>#}
{#                            </label>#}
{##}
{#                            <div class="d-flex align-items-center">#}
{#                                <button#}
{#                                        type="button"#}
{#                                        class="btn btn-outline-secondary btn-sm me-2"#}
{#                                        id="priceDecrement"#}
{#                                >#}
{#                                    <i class="fa-solid fa-minus"></i>#}
{#                                </button>#}
{##}
{#                                <input#}
{#                                        type="range"#}
{#                                        class="form-range flex-grow-1"#}
{#                                        name="max_price"#}
{#                                        id="priceRange"#}
{#                                        min="0"#}
{#                                        max="1000"#}
{#                                        value="{{ selected_max_price|default:1000 }}"#}
{#                                >#}
{##}
{#                                <button#}
{#                                        type="button"#}
{#                                        class="btn btn-outline-secondary btn-sm ms-2"#}
{#                                        id="priceIncrement"#}
{#                                >#}
{#                                    <i class="fa-solid fa-plus"></i>#}
{#                                </button>#}
{#                            </div>#}
{##}
{#                            <!--Discount Filter-->#}
{#                            <div class="form-check mb-4 mt-4">#}
{#                            <input#}
{#                                    class="form-check-input"#}
{#                                    type="checkbox"#}
{#                                    id="onsaleCheckbox"#}
{#                                    name="discount"#}
{#                                    value="1"#}
{#                                    {% if request.GET.discount %}checked{% endif %}#}
{#                            >#}
{#                            <label class="form-check-label" for="onsaleCheckbox">#}
{#                                <strong>On sale </strong>#}
{#                            </label>#}
{#                        </div>#}
{##}
{##}
{#                            <!-- Ordinamento -->#}
{#                            <h6 class ="mt-3">Order by</h6>#}
{#                            <select class="form-select mb-4" name="order">#}
{#                                <option value="" {% if not selected_order %}selected{% endif %}>Predefinito</option>#}
{#                                <option value="1" {% if selected_order == '1' %}selected{% endif %}>Prezzo: crescente</option>#}
{#                                <option value="2" {% if selected_order == '2' %}selected{% endif %}>Prezzo: decrescente</option>#}
{#                                <option value="3" {% if selected_order == '3' %}selected{% endif %}>Più recenti</option>#}
{#                            </select>#}
{##}
{#                            <button type="submit" class="btn btn-sm btn-outline-dark mt-2">Apply filters   <i class="fa-solid fa-arrow-right"></i></button>#}
{#                        </form>#}
{#                    </div>#}
{#                </div>#}
            </div>

            <!-- Colonna Destra: Griglia Prodotti -->
            <div class="col-lg-9">
                <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
                    {% for product in page_obj|default:products %}
                        <div class="col">
                            {% include "products/product_card.html" with product=product %}

                            {#                            <div class="card h-100 text-center shadow-sm">#}
{#                                <a href="#">#}
{#                                    <img src="{{ product.get_main_image }}" class="card-img-top p-3" alt="{{ product.name }}" style="height: 250px; width: 250px" >#}
{#                                </a>#}
{#                                <div class="card-body d-flex flex-column">#}
{#                                    <h5 class="card-title">#}
{#                                        <a href="#" class="text-decoration-none text-dark">{{ product.name|default:"product_name" }}</a>#}
{#                                    </h5>#}
{##}
{#                                    <p>{{ product.short_description|default:"Short description" }}</p>#}
{#                                    <p class="card-text fw-bold text-primary fs-5 mt-auto">€{{ product.price|default:"49.99" }}</p>#}
{#                                    {% if product.stock == 0 %}#}
{#                                        <p class="text-danger fw-bold">Out of Stock</p>#}
{#                                    {% else %}#}
{#                                        <div class="d-flex justify-content-center">#}
{#                                            <span class="badge bg-success w-30">In stock: {{ product.stock }}</span>#}
{#                                        </div>#}
{#                                    {% endif %}#}
{#                                        <form method="post" action="{% url 'product_detail' product.slug %}" class="mt-2">#}
{#                                            {% csrf_token %}#}
{#                                            <button type="submit" class="btn btn-primary w-100">View Details</button>#}
{#                                        </form>#}
{#                                </div>#}
{#                            </div>#}
                        </div>
                    {% empty %}
                        <div class="col-12">
                            <p class="text-center">No product found.</p>
                        </div>
                    {% endfor %}
                    {# Fine del loop #}
                </div>

                <!-- Paginazione -->
                {% if page_obj.has_other_pages %}
                    <nav aria-label="Page navigation" class="mt-5 d-flex justify-content-center">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link"
                                       href="?{% if get_params %}{{ get_params }}&{% endif %}page={{ page_obj.previous_page_number }}">
                                        Previous
                                    </a>
                                </li>
                            {% else %}
                                <li class="page-item disabled"><span class="page-link">Previous</span></li>
                            {% endif %}

                            {% for i in page_obj.paginator.page_range %}
                                {% if page_obj.number == i %}
                                    <li class="page-item active"><span class="page-link">{{ i }}</span></li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="?{% if get_params %}{{ get_params }}&{% endif %}page={{ i }}">
                                            {{ i }}
                                        </a>
                                    </li>
                                {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link"
                                       href="?{% if get_params %}{{ get_params }}&{% endif %}page={{ page_obj.next_page_number }}">
                                        Next
                                    </a>
                                </li>
                            {% else %}
                                <li class="page-item disabled"><span class="page-link">Next</span></li>
                            {% endif %}
                        </ul>
                    </nav>

                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}
{% block footer_js %}
    <script src="{% static 'js/product/price_slider.js' %}"></script>
{% endblock footer_js %}